library(ggplot2)
library(VGAM)
ss <- seq(1.1, 10, 0.001)
zetas <- zeta(ss)
d <- data.frame(s=ss, zeta=zetas)
ggplot(d, aes(x=s, y=zeta)) + geom_line() + theme_minimal() + xlab(expression(s)) + ylab(expression(zeta(s))) + ggtitle(expression(zeta(s) ~ "for" ~ s > 1))
ggsave("zetagreater1.pdf", path="/home/luke/tlk/millenniumprizes/", width=8, height=8, units="in", device="pdf")
ss <- seq(-10, 10, 0.001)
zetas <- zeta(ss)
d <- data.frame(s=ss, zeta=zetas)
ggplot(d, aes(x=s, y=zeta)) + geom_line() + theme_minimal() + xlab(expression(s)) + ylab(expression(zeta(s))) + ggtitle(expression(zeta(s) ~ "for real" ~ s)) + ylim(-10, 10)
ggsave("zetareal.pdf", path="/home/luke/tlk/millenniumprizes/", width=8, height=8, units="in", device="pdf")
# ss <- complex(real=seq(1.1, 10, 0.001), imaginary = 2)
# zetas <- zeta(ss)
# d <- data.frame(s=Mod(ss), zeta=zetas, modulus=Mod(zetas))
# ggplot(d, aes(x=s, y=modulus)) + geom_line() + theme_minimal() + xlab(expression(s)) + ylab(expression(zeta(s))) + ggtitle(expression(zeta(s) ~ "for real" ~ s)) + ylim(-10, 10)
# ggsave("zetacomplexpoint1.pdf", path="/home/luke/tlk/millenniumprizes/", width=8, height=8, units="in", device="pdf")

